---
language: R
cache: packages
r:
  - oldrel
  - release
  - devel
install:
- R -e "install.packages('testthat')"
- R -e "install.packages('jsonlite')"
- R -e "install.packages('lintr')"
- R -e "install.packages('magrittr')"
- R -e "install.packages('microbenchmark')"
script:
- bin/fetch-configlet
- bin/configlet lint .
- R -e "source('bin/run_tests.R')"
- R -e "source('bin/run_lints.R')"
