# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Requires scripts:
# - bin/run_tests.R

name: Exercise tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "exercises/**"
      - "bin/run_tests.R"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "exercises/**"
      - "bin/run_tests.R"
      - ".github/workflows/ci.yml"

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e
        with:
          r-version: 4.5.2

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e
        with:
          cache-version: 2
          packages: |
            testthat
            jsonlite
            dplyr
            stringr
            purrr
            tibble
            lubridate
            forcats

      - name: Run exercism/r ci (runs tests) for all exercises
        run: |
          source("bin/run_tests.R")
        shell: Rscript {0}
