# This workflow will do a clean install of the dependencies and run the linter
#
# Requires scripts:
# - bin/run_lints.R

name: Lint exercises

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: r-lib/actions/setup-r@a51a8012b0aab7c32ef9d19bf54da93f3254335e
        with:
          r-version: 4.3.1

      - uses: r-lib/actions/setup-r-dependencies@a51a8012b0aab7c32ef9d19bf54da93f3254335e
        with:
          cache-version: 1
          packages: |
            lintr

      - name: Run exercism/r ci pre-check (checks config, lint code) for all exercises
        run: |
          source("bin/run_lints.R")
        shell: Rscript {0}
